### ISSUE TITLE
Endless Sky - add request

### ISSUE THREAD

**Issue by endless-sky** [leereilly/games#114]
[Endless Sky](https://github.com/endless-sky/endless-sky) - a space trading and combat game similar to the classic Escape Velocity series.

Native (Linux, OS X, or Windows).

Category: probably "Sandbox", although it has Arcade and RPG elements as well.

https://github.com/endless-sky/endless-sky

**Comment by leereilly** [comment]
Thanks - added it under the Sandbox category :metal:

Cheers,
  Lee :beers:
