### ISSUE TITLE
List Addition: OpenNotrium

### ISSUE THREAD

**Issue by Enet4** [leereilly/games#181]
[OpenNotrium](https://github.com/verhoevenv/OpenNotrium) is an open-source (GPLv3) version of [Notrium](http://www.instantkingdom.com/notrium/), a top-down survival game made by Ville Mönkönnen in 2003. The source code was provided and later on published by @verhoevenv under GPLv3 in 2014.

Repository: https://github.com/verhoevenv/OpenNotrium

A closed-source version, maintained by the original author, is available on Steam: http://store.steampowered.com/app/349100/

It doesn't seem to fit in on any of the available game genres on the list of native desktop games. Should there be a new "Others" category for this case?

**Comment by leereilly** [comment]
Addressed in #182.
