### ISSUE TITLE
List Addition: I Spy A Ghost

### ISSUE THREAD

**Issue by OmarShehata** [leereilly/games#198]
This is a game I made for Ludum Dare which got 4th place in innovation. It's an HTML5 experimental multiplayer game made with Phaser.

https://github.com/OmarShehata/I-Spy-A-Ghost

![gameplay](https://raw.githubusercontent.com/OmarShehata/I-Spy-A-Ghost/master/Assets/screenshots/gameplay_2.gif)

**Comment by leereilly** [comment]
Awesome - thanks for the suggestion. I remember playing this when the judging began. Added via d145cc1f8789ba14226ec0de8e6700c1e486b66c  👻
