### ISSUE TITLE
List Addition: NetHack

### ISSUE THREAD

**Issue by inferno986return** [leereilly/games#226]
NetHack - Roguelike game, descendant of the original Rogue and one of the oldest games in active development.

https://en.wikipedia.org/wiki/NetHack
https://github.com/NetHack/NetHack

**Comment by DJgamer98** [comment]
I made a PR which adds NetHack and DCSS.
https://github.com/leereilly/games/pull/239

**Comment by Translator5** [comment]
:closed_book: // close issue?
