### ISSUE TITLE
I recommend sliding puzzle

### ISSUE THREAD

**Issue by rjopek** [leereilly/games#392]
Hi,
It is possible to add a game to the list?
https://github.com/rjopek/games/tree/master/sliding%20puzzle

![slidingpuzzle_ubuntu](https://cloud.githubusercontent.com/assets/10331874/25811158/9d93ad88-3412-11e7-9b98-9adaabe3aeef.png)

**Comment by Translator5** [comment]
done: https://github.com/Translator5/games/commit/d3090654ae55004e127308d80da75d070120c4f6

**Comment by rjopek** [comment]
Thank
