### ISSUE TITLE
Add Experience Value 2

### ISSUE THREAD

**Issue by rjopek** [leereilly/games#420]
Logic Games Experience Value 2,

This game is largely inspired by a 1989 DOS game called Greed, which had a similar experience and visual elements to this project. The goal of this game is to try to eat as much as possible of the board before munching yourself into a corner.

https://github.com/rjopek/games/tree/master/expervalue/expervalue2

Please include in the list.
 Rafał

**Comment by Translator5** [comment]
Wouldn't you like to merge all your games to one entry
`* [Rjopek Minigames](https://github.com/rjopek/games) - Multi platform games for Harbour programming language.
`

**Comment by rjopek** [comment]
Yes, that is a good idea.

Thanks a lot
Rafał
