### ISSUE TITLE
Update to the list - libRocket

### ISSUE THREAD

**Issue by noam-c** [leereilly/games#62]
libRocket is a UI middleware library that allows people to write UIs in RML/RCSS, which are based on HTML/CSS.
It's not strictly for games but that seems to be the primary use case. I believe it qualifies for a list of frameworks that speed game development, but it's up to the list maintainers.
The repo is at: https://github.com/librocket/librocket

**Comment by oskar-j** [comment]
:+1:  Imho it's ok to add it, there are similiar frameworks on our "games" crowdsourced list. Especialy if you check the librocket website - it's oss, cross-platform and used mostly by games. Simply add it to your fork and make a pull request. @leereilly will decide on this afterall

**Comment by noam-c** [comment]
Thank you!
