### ISSUE TITLE
I have been making a script json2markdown

### ISSUE THREAD

**Issue by mdtrooper** [leereilly/games#80]
Hi.

The last months, I was seeing how to grow the markdown file.

And I thought that maybe it is good separate the data and "the format" (I don't know the word in english sorry).

And I think in to save the data in JSON file and for the template in Mustache syntax (all tecnologies are standar).

Well, I started to develop it.

You can check the progress in:

https://github.com/mdtrooper/games/tree/json_data

There are not all games, it is only some of games from the list.

But for to continue, I want to write you:

Do you think is good "this method" for your master repository?

Is the people capable to fill a JSON instead a huge markdown file?

Regards, and thanks for the repository :beers:

**Comment by erayaydin** [comment]
Its would be great :+1:

**Comment by mdtrooper** [comment]
Thank you.

But I don't know how to work in this branch.

Because nobody (at least you, thanks again) say or write something.

**Comment by petarov** [comment]
Hey, this is a cool initiative! However, I personally think that it would be great to do exactly the opposite, i.e., some script that generates JSON data from the already existing Markdown file ;). Why? 

Well, GitHub already provides a pretty cool editor, so it is easier to add/remove entries via the editor in the MD file. The generated JSON file could be useful to feed some 3rd party service showing games & links added to this repo or to separate the data from the markdown as you suggested.

**Comment by mdtrooper** [comment]
Because this list is more as DB instead a doc.

For example, there are a lot of games unsorted or duplicated.

I think is good idea separate the data from representation.

**Comment by leereilly** [comment]
This is a wonderful idea, @mdtrooper (and I love the [implementation](https://github.com/mdtrooper/games/blob/json_data/scripts/processor.py)). I'd prefer to keep the `README.md` as plain markdown to keep it as approachable as possible – I'm sure there are plenty of people out there who aren't familiar with JSON and/or Python :smiley_cat: 

That said, the list I have here is getting pretty long. I'd love to have something that's searchable / filterable eventually...
