### ISSUE TITLE
Desperate Gods is not open source

### ISSUE THREAD

**Issue by polettix** [leereilly/games#92]
According to the relevant GitHub page, Desperate Gods (https://github.com/David20321/FTJ) is not open source:

> This repository is public for convenience and for personal use, but is not licensed for redistribution in whole or in part. We are open to issuing free permissive licenses for mods or code pieces, but you will just have to get our permission first [...]

**Comment by leereilly** [comment]
Thanks for bringing this up, @polettix. It *looks* like the author is encouraging forks via http://www.wolfire.com/desperate-gods:

![image](https://cloud.githubusercontent.com/assets/121322/6652758/f42f4b68-ca36-11e4-84a5-04fe64e572fb.png)


@David20321: would you like me to remove the link to Desperate Gods on https://github.com/leereilly/games?

**Comment by leereilly** [comment]
Closin
